In [1]:
import pandas as pd
import numpy as np
import duckdb
import sklearn
import xgboost
import lightgbm

print("Entorno correcto")

Entorno correcto

In [2]:
import duckdb

con = duckdb.connect("../data/raw/transfermarkt/transfermarkt-datasets.duckdb")

con.sql("SHOW TABLES")

┌───────────────────┐
│       name        │
│      varchar      │
├───────────────────┤
│ appearances       │
│ club_games        │
│ clubs             │
│ competitions      │
│ countries         │
│ game_events       │
│ game_lineups      │
│ games             │
│ national_teams    │
│ player_valuations │
│ players           │
│ transfers         │
│ version           │
└───────────────────┘
       13 rows

In [6]:
con.sql("DESCRIBE players")

┌──────────────────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│             column_name              │ column_type │  null   │   key   │ default │  extra  │
│               varchar                │   varchar   │ varchar │ varchar │ varchar │ varchar │
├──────────────────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ player_id                            │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ first_name                           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ last_name                            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ name                                 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ last_season                          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_club_id                      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ player_code                          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ country_of_birth                     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ city_of_birth                        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ country_of_citizenship               │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│     ·                                │    ·        │  ·      │  ·      │  ·      │  ·      │
│     ·                                │    ·        │  ·      │  ·      │  ·      │  ·      │
│     ·                                │    ·        │  ·      │  ·      │  ·      │  ·      │
│ agent_name                           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ image_url                            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ international_caps                   │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ international_goals                  │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_national_team_id             │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ url                                  │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_club_domestic_competition_id │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_club_name                    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ market_value_in_eur                  │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ highest_market_value_in_eur          │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
└──────────────────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
  26 rows (20 shown)                                                               6 columns

In [9]:
con.sql("DESCRIBE appearances")

┌────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│      column_name       │ column_type │  null   │   key   │ default │  extra  │
│        varchar         │   varchar   │ varchar │ varchar │ varchar │ varchar │
├────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ appearance_id          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ game_id                │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ player_id              │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ player_club_id         │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ player_current_club_id │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ date                   │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ player_name            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ competition_id         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ yellow_cards           │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ red_cards              │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ goals                  │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ assists                │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ minutes_played         │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
└────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
  13 rows                                                            6 columns

In [10]:
con.sql("DESCRIBE player_valuations")

┌─────────────────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│             column_name             │ column_type │  null   │   key   │ default │  extra  │
│               varchar               │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ player_id                           │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ date                                │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ market_value_in_eur                 │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_club_name                   │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_club_id                     │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ player_club_domestic_competition_id │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [11]:
con.sql("DESCRIBE transfers")

┌─────────────────────┬───────────────┬─────────┬─────────┬─────────┬─────────┐
│     column_name     │  column_type  │  null   │   key   │ default │  extra  │
│       varchar       │    varchar    │ varchar │ varchar │ varchar │ varchar │
├─────────────────────┼───────────────┼─────────┼─────────┼─────────┼─────────┤
│ player_id           │ INTEGER       │ YES     │ NULL    │ NULL    │ NULL    │
│ transfer_date       │ DATE          │ YES     │ NULL    │ NULL    │ NULL    │
│ transfer_season     │ VARCHAR       │ YES     │ NULL    │ NULL    │ NULL    │
│ from_club_id        │ INTEGER       │ YES     │ NULL    │ NULL    │ NULL    │
│ to_club_id          │ INTEGER       │ YES     │ NULL    │ NULL    │ NULL    │
│ from_club_name      │ VARCHAR       │ YES     │ NULL    │ NULL    │ NULL    │
│ to_club_name        │ VARCHAR       │ YES     │ NULL    │ NULL    │ NULL    │
│ transfer_fee        │ DECIMAL(18,3) │ YES     │ NULL    │ NULL    │ NULL    │
│ market_value_in_eur │ DECIMAL(18,3) │ YES     │ NULL    │ NULL    │ NULL    │
│ player_name         │ VARCHAR       │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────────────┴───────────────┴─────────┴─────────┴─────────┴─────────┘
  10 rows                                                           6 columns

In [13]:
con.sql("SELECT * FROM players LIMIT 5")

┌───────────┬────────────┬──────────────┬────────────────────┬─────────────┬─────────────────┬────────────────────┬────────────────────┬───────────────┬────────────────────────┬─────────────────────┬────────────────┬────────────┬─────────┬──────────────┬──────────────────────────┬──────────────────────┬───────────────────────────────────────────────────────────────────────────────┬────────────────────┬─────────────────────┬──────────────────────────┬──────────────────────────────────────────────────────────────────────┬──────────────────────────────────────┬─────────────────────────────────────────────────────────┬─────────────────────┬─────────────────────────────┐
│ player_id │ first_name │  last_name   │        name        │ last_season │ current_club_id │    player_code     │  country_of_birth  │ city_of_birth │ country_of_citizenship │    date_of_birth    │  sub_position  │  position  │  foot   │ height_in_cm │ contract_expiration_date │      agent_name      │                                   image_url                                   │ international_caps │ international_goals │ current_national_team_id │                                 url                                  │ current_club_domestic_competition_id │                    current_club_name                    │ market_value_in_eur │ highest_market_value_in_eur │
│   int32   │  varchar   │   varchar    │      varchar       │   varchar   │     varchar     │      varchar       │      varchar       │    varchar    │        varchar         │      timestamp      │    varchar     │  varchar   │ varchar │    int32     │        timestamp         │       varchar        │                                    varchar                                    │       int32        │        int32        │         varchar          │                               varchar                                │               varchar                │                         varchar                         │        int32        │            int32            │
├───────────┼────────────┼──────────────┼────────────────────┼─────────────┼─────────────────┼────────────────────┼────────────────────┼───────────────┼────────────────────────┼─────────────────────┼────────────────┼────────────┼─────────┼──────────────┼──────────────────────────┼──────────────────────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────┼─────────────────────┼──────────────────────────┼──────────────────────────────────────────────────────────────────────┼──────────────────────────────────────┼─────────────────────────────────────────────────────────┼─────────────────────┼─────────────────────────────┤
│        10 │ Miroslav   │ Klose        │ Miroslav Klose     │ 2015        │ 398             │ miroslav-klose     │ Poland             │ Opole         │ Germany                │ 1978-06-09 00:00:00 │ Centre-Forward │ Attack     │ right   │          184 │ NULL                     │ ASBW Sport Marketing │ https://img.a.transfermarkt.technology/portrait/header/10-1448468291.jpg?lm=1 │               NULL │                NULL │ NULL                     │ https://www.transfermarkt.co.uk/miroslav-klose/profil/spieler/10     │ IT1                                  │ Società Sportiva Lazio S.p.A.                           │             1000000 │                    30000000 │
│        26 │ Roman      │ Weidenfeller │ Roman Weidenfeller │ 2017        │ 16              │ roman-weidenfeller │ Germany            │ Diez          │ Germany                │ 1980-08-06 00:00:00 │ Goalkeeper     │ Goalkeeper │ left    │          190 │ NULL                     │ Neubauer 13 GmbH     │ https://img.a.transfermarkt.technology/portrait/header/26-1502448725.jpg?lm=1 │               NULL │                NULL │ NULL                     │ https://www.transfermarkt.co.uk/roman-weidenfeller/profil/spieler/26 │ L1                                   │ Borussia Dortmund                                       │              750000 │                     8000000 │
│        65 │ Dimitar    │ Berbatov     │ Dimitar Berbatov   │ 2015        │ 1091            │ dimitar-berbatov   │ Bulgaria           │ Blagoevgrad   │ Bulgaria               │ 1981-01-30 00:00:00 │ Centre-Forward │ Attack     │ NULL    │         NULL │ NULL                     │ CSKA-AS-23 Ltd.      │ https://img.a.transfermarkt.technology/portrait/header/65-1683670068.jpg?lm=1 │               NULL │                NULL │ NULL                     │ https://www.transfermarkt.co.uk/dimitar-berbatov/profil/spieler/65   │ GR1                                  │ Panthessalonikios Athlitikos Omilos Konstantinoupoliton │             1000000 │                    34500000 │
│        77 │ NULL       │ Lúcio        │ Lúcio              │ 2012        │ 506             │ lucio              │ Brazil             │ Brasília      │ Brazil                 │ 1978-05-08 00:00:00 │ Centre-Back    │ Defender   │ NULL    │         NULL │ NULL                     │ NULL                 │ https://img.a.transfermarkt.technology/portrait/header/77-1458201664.jpg?lm=1 │               NULL │                NULL │ NULL                     │ https://www.transfermarkt.co.uk/lucio/profil/spieler/77              │ IT1                                  │ Juventus FC                                             │              200000 │                    24500000 │
│        80 │ Tom        │ Starke       │ Tom Starke         │ 2017        │ 27              │ tom-starke         │ East Germany (GDR) │ Freital       │ Germany                │ 1981-03-18 00:00:00 │ Goalkeeper     │ Goalkeeper │ right   │          194 │ NULL                     │ IFM                  │ https://img.a.transfermarkt.technology/portrait/header/80-1471439914.JPG?lm=1 │               NULL │                NULL │ NULL                     │ https://www.transfermarkt.co.uk/tom-starke/profil/spieler/80         │ L1                                   │ Bayern Munich                                           │              100000 │                     3000000 │
└───────────┴────────────┴──────────────┴────────────────────┴─────────────┴─────────────────┴────────────────────┴────────────────────┴───────────────┴────────────────────────┴─────────────────────┴────────────────┴────────────┴─────────┴──────────────┴──────────────────────────┴──────────────────────┴───────────────────────────────────────────────────────────────────────────────┴────────────────────┴─────────────────────┴──────────────────────────┴──────────────────────────────────────────────────────────────────────┴──────────────────────────────────────┴─────────────────────────────────────────────────────────┴─────────────────────┴─────────────────────────────┘

In [20]:
con.sql("SELECT last_name FROM players WHERE last_season = '2025'")

┌────────────────────────┐
│       last_name        │
│        varchar         │
├────────────────────────┤
│ Guerrero               │
│ Milner                 │
│ Tsokanis               │
│ Hofmann                │
│ García                 │
│ Cristiano Ronaldo      │
│ Luiz Gustavo           │
│ Funes Mori             │
│ Carole                 │
│ Banega                 │
│   ·                    │
│   ·                    │
│   ·                    │
│ Banks                  │
│ Torres                 │
│ Marchiori              │
│ Lepasa                 │
│ Sepúlveda              │
│ Martel                 │
│ Moreno                 │
│ Ould-Chikh             │
│ de Lucas               │
│ Teles                  │
└────────────────────────┘
          ? rows
  (>9999 rows, 20 shown)

In [21]:
con.sql("""
SELECT 
    last_season,
    COUNT(*) AS players
FROM players
GROUP BY last_season
ORDER BY last_season DESC
""")

┌─────────────┬─────────┐
│ last_season │ players │
│   varchar   │  int64  │
├─────────────┼─────────┤
│ 2025        │   22292 │
│ 2024        │    6075 │
│ 2023        │    2092 │
│ 2022        │    1877 │
│ 2021        │    1817 │
│ 2020        │    1843 │
│ 2019        │    1566 │
│ 2018        │    2065 │
│ 2017        │    1661 │
│ 2016        │    1831 │
│ 2015        │    1651 │
│ 2014        │    1660 │
│ 2013        │    2061 │
│ 2012        │    1658 │
└─────────────┴─────────┘
  14 rows     2 columns

In [22]:
con.sql("""
SELECT 
    MIN(transfer_date) AS first_transfer,
    MAX(transfer_date) AS last_transfer,
    COUNT(*) AS total_transfers
FROM transfers
""")

┌────────────────┬───────────────┬─────────────────┐
│ first_transfer │ last_transfer │ total_transfers │
│      date      │     date      │      int64      │
├────────────────┼───────────────┼─────────────────┤
│ 1993-07-01     │ 2030-06-30    │          175165 │
└────────────────┴───────────────┴─────────────────┘

In [23]:
con.sql("""
SELECT 
    MIN(date) AS first_valuation,
    MAX(date) AS last_valuation,
    COUNT(*) AS total_valuations
FROM player_valuations
""")

┌─────────────────┬────────────────┬──────────────────┐
│ first_valuation │ last_valuation │ total_valuations │
│      date       │      date      │      int64       │
├─────────────────┼────────────────┼──────────────────┤
│ 2000-01-20      │ 2026-06-12     │           656301 │
└─────────────────┴────────────────┴──────────────────┘

In [26]:
con.sql("""
SELECT *
FROM transfers
WHERE transfer_date >= '2028-01-01'
ORDER BY transfer_date
LIMIT 20
""")

┌───────────┬───────────────┬─────────────────┬──────────────┬────────────┬─────────────────┬──────────────┬───────────────┬─────────────────────┬───────────────────┐
│ player_id │ transfer_date │ transfer_season │ from_club_id │ to_club_id │ from_club_name  │ to_club_name │ transfer_fee  │ market_value_in_eur │    player_name    │
│   int32   │     date      │     varchar     │    int32     │   int32    │     varchar     │   varchar    │ decimal(18,3) │    decimal(18,3)    │      varchar      │
├───────────┼───────────────┼─────────────────┼──────────────┼────────────┼─────────────────┼──────────────┼───────────────┼─────────────────────┼───────────────────┤
│    645842 │ 2028-02-02    │ 27/28           │         6505 │      19684 │ Gimcheon Sangmu │ Jeju SK      │         0.000 │          150000.000 │ Chan-gi An        │
│    677470 │ 2028-02-02    │ 27/28           │         6505 │       3535 │ Gimcheon Sangmu │ Ulsan HD     │         0.000 │          400000.000 │ Yool Heo          │
│    709155 │ 2028-02-02    │ 27/28           │         6505 │      19684 │ Gimcheon Sangmu │ Jeju SK      │         0.000 │          325000.000 │ Jae-hyeok Oh      │
│    728133 │ 2028-02-02    │ 27/28           │         6505 │      35759 │ Gimcheon Sangmu │ Bucheon FC   │         0.000 │          175000.000 │ Sang-hyeok Lee    │
│    730364 │ 2028-02-02    │ 27/28           │         6505 │      38898 │ Gimcheon Sangmu │ FC Anyang    │         0.000 │          150000.000 │ Gyu-hyeon Choe    │
│    746780 │ 2028-02-02    │ 27/28           │         6505 │       2996 │ Gimcheon Sangmu │ Incheon Utd. │         0.000 │          125000.000 │ Young-hun Kang    │
│    755355 │ 2028-02-02    │ 27/28           │         6505 │      30925 │ Gimcheon Sangmu │ Gwangju FC   │         0.000 │          350000.000 │ Jin-ho Kim        │
│    862094 │ 2028-02-02    │ 27/28           │         6505 │      21459 │ Gimcheon Sangmu │ Gangwon FC   │         0.000 │          400000.000 │ Jun-seok Song     │
│    929007 │ 2028-02-02    │ 27/28           │         6505 │      19684 │ Gimcheon Sangmu │ Jeju SK      │         0.000 │          350000.000 │ Jun-ha Kim        │
│    467994 │ 2030-06-30    │ 25/26           │         5621 │        749 │ Reggiana        │ FC Empoli    │         0.000 │          700000.000 │ Luca Belardinelli │
└───────────┴───────────────┴─────────────────┴──────────────┴────────────┴─────────────────┴──────────────┴───────────────┴─────────────────────┴───────────────────┘
  10 rows                                                                                                                                                 10 columns

In [3]:
path = "../data/raw/fbref_2025-2026/players_data-2025_2026.csv"

df_fbref = pd.read_csv(path)

df_fbref.shape

(2839, 102)

In [29]:
df_fbref.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,CrdY_stats_misc,CrdR_stats_misc,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,24.0,2000.0,37,30,...,3,0,0,20,51,5,37,17,27,0
1,2,Jerome Abbey,eng ENG,MF,Wolves,eng Premier League,15.0,2009.0,1,0,...,0,0,0,0,0,1,0,1,0,0
2,3,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,19.0,2006.0,3,2,...,0,0,0,3,1,0,3,2,4,0
3,4,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,19.0,2006.0,22,4,...,0,0,0,7,3,2,30,3,3,0
4,5,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,25.0,1999.0,8,1,...,1,0,0,3,0,0,1,2,1,0

In [31]:
cols = df_fbref.columns.tolist()
for col in cols:
    print(col)

Rk
Player
Nation
Pos
Squad
Comp
Age
Born
MP
Starts
Min
90s
Gls
Ast
G+A
G-PK
PK
PKatt
CrdY
CrdR
G+A-PK
Rk_stats_keeper
Nation_stats_keeper
Pos_stats_keeper
Comp_stats_keeper
Age_stats_keeper
Born_stats_keeper
MP_stats_keeper
Starts_stats_keeper
Min_stats_keeper
90s_stats_keeper
GA
GA90
SoTA
Saves
Save%
W
D
L
CS
CS%
PKatt_stats_keeper
PKA
PKsv
PKm
Rk_stats_shooting
Nation_stats_shooting
Pos_stats_shooting
Comp_stats_shooting
Age_stats_shooting
Born_stats_shooting
90s_stats_shooting
Gls_stats_shooting
Sh
SoT
SoT%
Sh/90
SoT/90
G/Sh
G/SoT
PK_stats_shooting
PKatt_stats_shooting
Rk_stats_playing_time
Nation_stats_playing_time
Pos_stats_playing_time
Comp_stats_playing_time
Age_stats_playing_time
Born_stats_playing_time
MP_stats_playing_time
Min_stats_playing_time
Mn/MP
Min%
90s_stats_playing_time
Starts_stats_playing_time
Mn/Start
Compl
Subs
Mn/Sub
unSub
PPM
onG
onGA
+/-
+/-90
On-Off
Rk_stats_misc
Nation_stats_misc
Pos_stats_misc
Comp_stats_misc
Age_stats_misc
Born_stats_misc
90s_stats_misc
CrdY_stats_misc
CrdR_stats_misc
2CrdY
Fls
Fld
Off
Crs
Int
TklW
OG

In [33]:
df_fbref.info()

<class 'pandas.DataFrame'>
RangeIndex: 2839 entries, 0 to 2838
Columns: 102 entries, Rk to OG
dtypes: float64(45), int64(40), str(17)
memory usage: 2.2 MB

In [42]:
nan_dict = {}

for col in cols:
    nan_dict[col] = len(df_fbref[df_fbref[col].isna()])

nan_dict

{'Rk': 0,
 'Player': 0,
 'Nation': 3,
 'Pos': 0,
 'Squad': 0,
 'Comp': 0,
 'Age': 2,
 'Born': 2,
 'MP': 0,
 'Starts': 0,
 'Min': 0,
 '90s': 0,
 'Gls': 0,
 'Ast': 0,
 'G+A': 0,
 'G-PK': 0,
 'PK': 0,
 'PKatt': 0,
 'CrdY': 0,
 'CrdR': 0,
 'G+A-PK': 0,
 'Rk_stats_keeper': 2645,
 'Nation_stats_keeper': 2645,
 'Pos_stats_keeper': 2645,
 'Comp_stats_keeper': 2645,
 'Age_stats_keeper': 2645,
 'Born_stats_keeper': 2645,
 'MP_stats_keeper': 2645,
 'Starts_stats_keeper': 2645,
 'Min_stats_keeper': 2645,
 '90s_stats_keeper': 2645,
 'GA': 2645,
 'GA90': 2645,
 'SoTA': 2645,
 'Saves': 2645,
 'Save%': 2649,
 'W': 2645,
 'D': 2645,
 'L': 2645,
 'CS': 2645,
 'CS%': 2651,
 'PKatt_stats_keeper': 2645,
 'PKA': 2645,
 'PKsv': 2645,
 'PKm': 2645,
 'Rk_stats_shooting': 0,
 'Nation_stats_shooting': 3,
 'Pos_stats_shooting': 0,
 'Comp_stats_shooting': 0,
 'Age_stats_shooting': 2,
 'Born_stats_shooting': 2,
 '90s_stats_shooting': 0,
 'Gls_stats_shooting': 0,
 'Sh': 0,
 'SoT': 0,
 'SoT%': 490,
 'Sh/90': 0,
 'SoT/90': 0,
 'G/Sh': 490,
 'G/SoT': 826,
 'PK_stats_shooting': 0,
 'PKatt_stats_shooting': 0,
 'Rk_stats_playing_time': 0,
 'Nation_stats_playing_time': 3,
 'Pos_stats_playing_time': 0,
 'Comp_stats_playing_time': 0,
 'Age_stats_playing_time': 2,
 'Born_stats_playing_time': 2,
 'MP_stats_playing_time': 0,
 'Min_stats_playing_time': 0,
 'Mn/MP': 0,
 'Min%': 0,
 '90s_stats_playing_time': 0,
 'Starts_stats_playing_time': 0,
 'Mn/Start': 362,
 'Compl': 0,
 'Subs': 0,
 'Mn/Sub': 377,
 'unSub': 0,
 'PPM': 0,
 'onG': 0,
 'onGA': 0,
 '+/-': 0,
 '+/-90': 0,
 'On-Off': 25,
 'Rk_stats_misc': 0,
 'Nation_stats_misc': 3,
 'Pos_stats_misc': 0,
 'Comp_stats_misc': 0,
 'Age_stats_misc': 2,
 'Born_stats_misc': 2,
 '90s_stats_misc': 0,
 'CrdY_stats_misc': 0,
 'CrdR_stats_misc': 0,
 '2CrdY': 0,
 'Fls': 0,
 'Fld': 0,
 'Off': 0,
 'Crs': 0,
 'Int': 0,
 'TklW': 0,
 'OG': 0}

### **unified_player_stats data**

In [3]:
path = "../venv/Lib/site-packages/data/unified_player_stats.csv"

df = pd.read_csv(path)

df.shape

C:\Users\salit\AppData\Local\Temp\ipykernel_25140\768013171.py:3: DtypeWarning: Columns (0: pos) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

(22297, 149)

##### Mini-EDA unified_player_stats data

In [5]:
df.league.value_counts()

league
All Competitions            3361
UEFA Europa League          2740
UEFA Champions League       2477
England EFL Championship    2189
Spain La Liga               1783
Italy Serie A               1775
England Premier League      1668
Portugal Primeira Liga      1645
France Ligue 1              1618
Netherlands Eredivisie      1567
Germany Bundesliga          1474
Name: count, dtype: int64

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22297 entries, 0 to 22296
Columns: 149 entries, understat_id to npxg_overperformance
dtypes: bool(2), float64(131), int64(8), str(8)
memory usage: 26.9 MB

In [48]:
df["season"].value_counts().sort_index()

season
2023-2024    7209
2024-2025    7510
2025-2026    7578
Name: count, dtype: int64

In [45]:
df.head()

,understat_id,player,team,pos,games,minutes,goals,assists,shots,key_passes,...,xg_chain_per90,xg_buildup_per90,shots_per90,key_passes_per90,tackles_won_per90,interceptions_per90,big_chances_created_per90,dribbles_per90,xg_overperformance,npxg_overperformance
0,11295.0,David Datro Fofana,"1. FC Union Berlin,Burnley,Union Berlin",F S,31,1758,6,1,53,18,...,0.496,0.068,2.714,0.922,0.666,0.051,0.154,1.997,-2.99,-3.09
1,3699.0,Aissa Laidouni,"1. FC Union Berlin,Union Berlin",M S,29,1305,0,4,15,15,...,0.334,0.208,1.034,1.034,1.172,0.897,0.276,1.103,-0.98,-0.77
2,8017.0,Alex Kral,"1. FC Union Berlin,Union Berlin",D M S,30,1587,1,1,21,7,...,0.266,0.173,1.191,0.397,1.021,0.737,0.113,0.340,-0.78,-1.72
3,11236.0,Aljoscha Kemlein,"1. FC Union Berlin,Union Berlin",S,3,36,0,0,1,0,...,1.686,1.604,2.500,0.000,0.000,0.000,0.000,2.500,-0.03,-0.03
4,10751.0,Brenden Aaronson,"1. FC Union Berlin,Union Berlin",F M S,36,1337,2,2,22,22,...,0.500,0.226,1.480,1.480,1.211,0.336,0.269,2.355,-0.86,-0.38

In [48]:
df["league"].value_counts()

league
All Competitions            3361
UEFA Europa League          2740
UEFA Champions League       2477
England EFL Championship    2189
Spain La Liga               1783
Italy Serie A               1775
England Premier League      1668
Portugal Primeira Liga      1645
France Ligue 1              1618
Netherlands Eredivisie      1567
Germany Bundesliga          1474
Name: count, dtype: int64

In [49]:
df.groupby(["season", "league"]).size()

season     league
2023-2024  All Competitions            1070
           England EFL Championship     705
           England Premier League       569
           France Ligue 1               523
           Germany Bundesliga           494
           Italy Serie A                590
           Netherlands Eredivisie       516
           Portugal Primeira Liga       516
           Spain La Liga                596
           UEFA Champions League        721
           UEFA Europa League           909
2024-2025  All Competitions            1131
           England EFL Championship     736
           England Premier League       562
           France Ligue 1               542
           Germany Bundesliga           481
           Italy Serie A                599
           Netherlands Eredivisie       520
           Portugal Primeira Liga       562
           Spain La Liga                588
           UEFA Champions League        878
           UEFA Europa League           911
2025-2026  All Competitions            1160
           England EFL Championship     748
           England Premier League       537
           France Ligue 1               553
           Germany Bundesliga           499
           Italy Serie A                586
           Netherlands Eredivisie       531
           Portugal Primeira Liga       567
           Spain La Liga                599
           UEFA Champions League        878
           UEFA Europa League           920
dtype: int64

In [52]:
df.groupby(["player", "season"]).size().describe()

count    15754.000000
mean         1.415323
std          0.821440
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          6.000000
dtype: float64

In [50]:
df["pos"].value_counts()

pos
D S        2419
M S        2144
F M S      1493
S          1121
D M S       898
F S         897
GK          631
D           455
D F M S     254
M           148
GK S        107
D M          58
F M          52
F            39
D F S        12
D F M         8
Name: count, dtype: int64

In [51]:
df["is_season_total"].value_counts(dropna=False)

is_season_total
False    18936
True      3361
Name: count, dtype: int64

In [53]:
df[df["is_season_total"] == True][
    ["player", "team", "league", "season", "games", "minutes"]
].head(20)

,player,team,league,season,games,minutes
0,David Datro Fofana,"1. FC Union Berlin,Burnley,Union Berlin",All Competitions,2023-2024,31,1758
1,Aissa Laidouni,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,29,1305
2,Alex Kral,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,30,1587
3,Aljoscha Kemlein,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,3,36
4,Brenden Aaronson,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,36,1337
5,Christopher Trimmel,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,29,1804
6,Danilho Doekhi,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,27,2420
7,Diogo Leite,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,38,3250
8,Frederik Rönnow,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,39,3510
9,Janik Haberer,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,26,1588
10,Josip Juranovic,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,26,1688
11,Jérôme Roussillon,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,27,973
12,Kevin Volland,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,31,1627
13,Leonardo Bonucci,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,10,727
14,Lucas Tousart,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,28,1829
15,Paul Jäckel,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,9,391
16,Rani Khedira,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,24,1670
17,Robin Gosens,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,36,2795
18,Robin Knoche,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,27,2190
19,Kevin Behrens,"1. FC Union Berlin,Union Berlin,Wolfsburg",All Competitions,2023-2024,36,2217

In [54]:
df[df["is_season_total"] == False][
    ["player", "team", "league", "season", "games", "minutes"]
].head(20)

,player,team,league,season,games,minutes
3361,Alex Pritchard,Birmingham City,England EFL Championship,2023-2024,32,1455
3362,Andre Dozzell,Birmingham City,England EFL Championship,2023-2024,35,2613
3363,Brandon Khela,Birmingham City,England EFL Championship,2023-2024,1,9
3364,Cody Drameh,Birmingham City,England EFL Championship,2023-2024,29,2273
3365,Dion Sanderson,Birmingham City,England EFL Championship,2023-2024,37,3301
3366,Emanuel Aiwu,Birmingham City,England EFL Championship,2023-2024,24,1957
3367,Emmanuel Longelo,Birmingham City,England EFL Championship,2023-2024,17,1025
3368,Ethan Laird,Birmingham City,England EFL Championship,2023-2024,25,2001
3369,Gary Gardner,Birmingham City,England EFL Championship,2023-2024,16,248
3370,George Hall,Birmingham City,England EFL Championship,2023-2024,8,150
3371,Ivan Šunjić,Birmingham City,England EFL Championship,2023-2024,36,2642
3372,Jay Stansfield,Birmingham City,England EFL Championship,2023-2024,43,3353
3373,John Ruddy,Birmingham City,England EFL Championship,2023-2024,44,3960
3374,Jordan James,Birmingham City,England EFL Championship,2023-2024,42,2347
3375,Juninho Bacuna,Birmingham City,England EFL Championship,2023-2024,45,2981
3376,Keshi Anderson,Birmingham City,England EFL Championship,2023-2024,20,1023
3377,Kevin Long,Birmingham City,England EFL Championship,2023-2024,17,1450
3378,Koji Miyoshi,Birmingham City,England EFL Championship,2023-2024,43,2522
3379,Krystian Bielik,Birmingham City,England EFL Championship,2023-2024,36,2987
3380,Lee Buchanan,Birmingham City,England EFL Championship,2023-2024,32,2733

In [56]:
jugadores_total = set(
    df[df["is_season_total"] == True]["player"]
)

jugadores_competiciones = set(
    df[df["is_season_total"] == False]["player"]
)

jugadores_sin_total = jugadores_competiciones - jugadores_total

len(jugadores_sin_total)

6463

In [55]:
df_total = df[df["is_season_total"] == True].copy()

df_total.groupby("season")["player"].nunique()

season
2023-2024    1069
2024-2025    1131
2025-2026    1160
Name: player, dtype: int64

#### **Creación dataset del rendimiento en ligas domésticas - Big 5**

En este dataset se recoge el rendimiento de los jugadores pertenecientes a equipos de las cinco grandes ligas europeas (England Premier League, Spain La Liga, Germany Bundesliga, Italy Serie A y France Ligue 1) exclusivamente en sus respectivas competiciones domésticas. Por tanto, se excluye el rendimiento obtenido en competiciones europeas, como la UEFA Champions League o la UEFA Europa League. Este rendimiento se recoge de forma independiente en otro dataset, que contempla el rendimiento de los jugadores en el conjunto de las competiciones disputadas durante la temporada.

In [6]:
DOMESTIC_LEAGUES = [
    "England Premier League",
    "Spain La Liga",
    "Germany Bundesliga",
    "Italy Serie A",
    "France Ligue 1"
]

df_domestic = df[df["league"].isin(DOMESTIC_LEAGUES)].copy()

In [7]:
df_domestic.shape

(8318, 149)

#### Comprobación de valores de features df_domestic

Validación de consistencia de IDs

In [8]:
df_domestic[[
    "understat_id",
    "sofascore_id",
    "player",
    "team",
    "season",
    "league"
]].head(20)

,understat_id,sofascore_id,player,team,season,league
5550,5603.0,839410.0,Aaron Ramsdale,Arsenal,2023-2024,England Premier League
5551,7298.0,846036.0,Ben White,Arsenal,2023-2024,England Premier League
5552,7322.0,934235.0,Bukayo Saka,Arsenal,2023-2024,England Premier League
5553,847.0,44760.0,Cédric Soares,Arsenal,2023-2024,England Premier League
5554,9676.0,581310.0,David Raya,Arsenal,2023-2024,England Premier League
5555,5553.0,856714.0,Declan Rice,Arsenal,2023-2024,England Premier League
5556,6482.0,858194.0,Eddie Nketiah,Arsenal,2023-2024,England Premier League
5557,7230.0,867445.0,Emile Smith-Rowe,Arsenal,2023-2024,England Premier League
5558,11132.0,1401702.0,Ethan Nwaneri,Arsenal,2023-2024,England Premier League
5559,11007.0,904835.0,Fábio Vieira,Arsenal,2023-2024,England Premier League
5560,5613.0,869792.0,Gabriel,Arsenal,2023-2024,England Premier League
5561,5543.0,794839.0,Gabriel Jesus,Arsenal,2023-2024,England Premier League
5562,7752.0,922573.0,Gabriel Martinelli,Arsenal,2023-2024,England Premier League
5563,10012.0,976037.0,Jakub Kiwior,Arsenal,2023-2024,England Premier League
5564,1389.0,132874.0,Jorginho,Arsenal,2023-2024,England Premier League
5565,11707.0,958959.0,Jurriën Timber,Arsenal,2023-2024,England Premier League
5566,5220.0,836705.0,Kai Havertz,Arsenal,2023-2024,England Premier League
5567,7698.0,135666.0,Leandro Trossard,Arsenal,2023-2024,England Premier League
5568,2517.0,547410.0,Martin Odegaard,Arsenal,2023-2024,England Premier League
5569,496.0,159675.0,Mohamed Elneny,Arsenal,2023-2024,England Premier League

In [9]:
multi_league = (
    df_domestic
    .groupby(["understat_id", "season"])["league"]
    .nunique()
    .sort_values(ascending=False)
)

multi_league[multi_league > 1].head(20)

understat_id  season
8821.0        2023-2024    2
7095.0        2024-2025    2
5743.0        2023-2024    2
              2024-2025    2
2117.0        2024-2025    2
8981.0        2023-2024    2
638.0         2024-2025    2
8429.0        2023-2024    2
643.0         2023-2024    2
5329.0        2025-2026    2
8200.0        2024-2025    2
8393.0        2024-2025    2
239.0         2025-2026    2
5221.0        2025-2026    2
65.0          2023-2024    2
8700.0        2025-2026    2
9105.0        2023-2024    2
8812.0        2023-2024    2
7882.0        2023-2024    2
7236.0        2023-2024    2
Name: league, dtype: int64

In [10]:
multi_league[multi_league > 1].shape

(212,)

In [11]:
multi_league[multi_league > 1].head(5).index

MultiIndex([(8821.0, '2023-2024'),
            (7095.0, '2024-2025'),
            (5743.0, '2023-2024'),
            (5743.0, '2024-2025'),
            (2117.0, '2024-2025')],
           names=['understat_id', 'season'])

In [12]:
df_domestic.groupby(
    ["understat_id", "season"]
)["league"].nunique().gt(1).sum()

np.int64(212)

In [13]:
df_domestic.groupby(
    ["sofascore_id", "season"]
)["league"].nunique().gt(1).sum()

np.int64(215)

In [14]:
df_domestic[["understat_id", "sofascore_id"]].isna().sum()

understat_id    0
sofascore_id    0
dtype: int64

In [15]:
understat_multi = (
    df_domestic
    .groupby(["understat_id", "season"])["league"]
    .nunique()
)

sofascore_multi = (
    df_domestic
    .groupby(["sofascore_id", "season"])["league"]
    .nunique()
)

sofascore_multi[sofascore_multi > 1].index

MultiIndex([(      0.0, '2023-2024'),
            (      0.0, '2024-2025'),
            (      0.0, '2025-2026'),
            (  44614.0, '2024-2025'),
            (  45923.0, '2025-2026'),
            (  48480.0, '2025-2026'),
            (  78152.0, '2023-2024'),
            ( 132645.0, '2025-2026'),
            ( 146101.0, '2023-2024'),
            ( 158615.0, '2025-2026'),
            ...
            (1493689.0, '2024-2025'),
            (1500263.0, '2025-2026'),
            (1503757.0, '2025-2026'),
            (1514800.0, '2025-2026'),
            (1526628.0, '2025-2026'),
            (1536811.0, '2025-2026'),
            (1606792.0, '2024-2025'),
            (1823916.0, '2025-2026'),
            (1884145.0, '2025-2026'),
            (1926085.0, '2025-2026')],
           names=['sofascore_id', 'season'], length=215)

In [18]:
understat_multi_players = (
    df_domestic
    .groupby(["player", "season"])["league"]
    .nunique()
)

sofascore_multi_players = (
    df_domestic
    .groupby(["player", "season"])["league"]
    .nunique()
)

In [19]:
(understat_multi_players > 1).sum()

np.int64(226)

In [20]:
(sofascore_multi_players > 1).sum()

np.int64(226)

Sofascore merge failed

In [34]:
df_domestic._ss_merge_failed.value_counts()

_ss_merge_failed
False    8309
True        9
Name: count, dtype: int64

Sofascore ratings

In [29]:
df_domestic[
    [
        "player",
        "season",
        "league",
        "sofascore_rating",
        "sofascore_rating_total",
        "sofascore_rating_count"
    ]
].head(20)

,player,season,league,sofascore_rating,sofascore_rating_total,sofascore_rating_count
5550,Aaron Ramsdale,2023-2024,England Premier League,6.63,39.8,6.0
5551,Ben White,2023-2024,England Premier League,7.26,261.2,36.0
5552,Bukayo Saka,2023-2024,England Premier League,7.72,270.2,35.0
5553,Cédric Soares,2023-2024,England Premier League,6.63,19.9,3.0
5554,David Raya,2023-2024,England Premier League,6.85,219.2,32.0
5555,Declan Rice,2023-2024,England Premier League,7.43,282.4,38.0
5556,Eddie Nketiah,2023-2024,England Premier League,6.89,179.1,26.0
5557,Emile Smith-Rowe,2023-2024,England Premier League,6.67,246.7,37.0
5558,Ethan Nwaneri,2023-2024,England Premier League,6.90,6.9,1.0
5559,Fábio Vieira,2023-2024,England Premier League,6.92,69.2,10.0
5560,Gabriel,2023-2024,England Premier League,7.27,232.5,32.0
5561,Gabriel Jesus,2023-2024,England Premier League,7.17,193.5,27.0
5562,Gabriel Martinelli,2023-2024,England Premier League,7.11,248.7,35.0
5563,Jakub Kiwior,2023-2024,England Premier League,6.95,111.2,16.0
5564,Jorginho,2023-2024,England Premier League,6.96,132.2,19.0
5565,Jurriën Timber,2023-2024,England Premier League,6.70,13.4,2.0
5566,Kai Havertz,2023-2024,England Premier League,7.23,267.4,37.0
5567,Leandro Trossard,2023-2024,England Premier League,7.06,240.0,34.0
5568,Martin Odegaard,2023-2024,England Premier League,6.99,167.8,24.0
5569,Mohamed Elneny,2023-2024,England Premier League,6.90,13.8,2.0

Comprobación de nulos en df_domestic

In [28]:
missing = (
    df_domestic.isna()
    .mean()
    .sort_values(ascending=False)
)

for row in missing:
    if row > 0:
        print(row)

##### Clasificación de features

In [16]:
rate_cols = [
    col for col in df_domestic.columns
    if any(term in col.lower() for term in [
        "_per90",
        "_pct",
        "conversion",
        "frequency",
        "overperformance"
    ])
]
rate_cols.remove('ground_duels_won_pct')
rate_cols.remove('set_piece_conversion')
rate_cols.remove("scoring_frequency")
rate_cols

['tackles_won_pct',
 'aerials_won_pct',
 'dribbles_pct',
 'duels_won_pct',
 'pass_completion_pct',
 'long_balls_pct',
 'crosses_pct',
 'goal_conversion_pct',
 'pen_conversion_pct',
 'passes_opp_half_pct',
 'passes_own_half_pct',
 'chipped_passes_pct',
 'shots_inside_box_conversion_pct',
 'shots_outside_box_conversion_pct',
 'goals_per90',
 'assists_per90',
 'npg_per90',
 'xg_per90',
 'xag_per90',
 'npxg_per90',
 'xg_chain_per90',
 'xg_buildup_per90',
 'shots_per90',
 'key_passes_per90',
 'tackles_won_per90',
 'interceptions_per90',
 'big_chances_created_per90',
 'dribbles_per90',
 'xg_overperformance',
 'npxg_overperformance']

In [17]:
numeric_cols = df_domestic.select_dtypes(include="number").columns.tolist()

numeric_cols

['understat_id',
 'games',
 'minutes',
 'goals',
 'assists',
 'shots',
 'key_passes',
 'yellow_cards',
 'red_cards',
 'npg',
 'xg',
 'xag',
 'npxg',
 'xg_chain',
 'xg_buildup',
 'ninety_s',
 'sofascore_id',
 'sofascore_team_id',
 'sofascore_rating',
 'sofascore_rating_total',
 'sofascore_rating_count',
 'totw_appearances',
 'starts',
 'tackles',
 'tackles_won',
 'tackles_won_pct',
 'interceptions',
 'clearances',
 'blocked_shots',
 'outfield_blocks',
 'errors_leading_to_goal',
 'errors_leading_to_shot',
 'dribbled_past',
 'aerials_won',
 'aerials_won_pct',
 'aerials_lost',
 'dribbles_completed',
 'dribbles_pct',
 'dribbles_attempted',
 'ground_duels_won',
 'ground_duels_won_pct',
 'duels_won',
 'duels_won_pct',
 'duels_lost',
 'passes_total',
 'passes_completed',
 'passes_inaccurate',
 'pass_completion_pct',
 'passes_final_third',
 'passes_opp_half',
 'passes_own_half',
 'passes_opp_half_total',
 'passes_own_half_total',
 'long_balls_total',
 'long_balls_completed',
 'long_balls_pct',
 'crosses_total',
 'crosses_completed',
 'crosses_pct',
 'chipped_passes_total',
 'chipped_passes_completed',
 'pass_to_assist',
 'attempt_assists',
 'big_chances_created',
 'big_chances_missed',
 'goals_inside_box',
 'goals_outside_box',
 'goals_headed',
 'goals_left_foot',
 'goals_right_foot',
 'goals_penalty',
 'goals_freekick',
 'own_goals',
 'goals_assists',
 'hit_woodwork',
 'shots_inside_box',
 'shots_outside_box',
 'shots_on_target',
 'shots_off_target',
 'shots_set_piece',
 'goal_conversion_pct',
 'scoring_frequency',
 'set_piece_conversion',
 'touches',
 'possession_lost',
 'possession_won_att_third',
 'dispossessed',
 'ball_recoveries',
 'fouls',
 'fouled',
 'offsides',
 'yellow_red_cards',
 'direct_red_cards',
 'pens_taken',
 'pens_conceded',
 'pens_won',
 'pen_conversion_pct',
 'pen_miss',
 'pen_post',
 'pen_on_target',
 'saves',
 'saves_caught',
 'saves_parried',
 'saves_inside_box',
 'saves_outside_box',
 'goals_conceded',
 'goals_conceded_inside_box',
 'goals_conceded_outside_box',
 'goals_prevented',
 'clean_sheets',
 'high_claims',
 'crosses_not_claimed',
 'punches',
 'runs_out',
 'runs_out_successful',
 'goal_kicks',
 'pens_saved',
 'pens_faced',
 'passes_opp_half_pct',
 'passes_own_half_pct',
 'chipped_passes_pct',
 'shots_inside_box_conversion_pct',
 'shots_outside_box_conversion_pct',
 'goals_per90',
 'assists_per90',
 'npg_per90',
 'xg_per90',
 'xag_per90',
 'npxg_per90',
 'xg_chain_per90',
 'xg_buildup_per90',
 'shots_per90',
 'key_passes_per90',
 'tackles_won_per90',
 'interceptions_per90',
 'big_chances_created_per90',
 'dribbles_per90',
 'xg_overperformance',
 'npxg_overperformance']

In [18]:
non_numeric_cols = df_domestic.select_dtypes(exclude="number").columns.tolist()

non_numeric_cols

['player',
 'team',
 'pos',
 'league',
 'season',
 '_ss_merge_failed',
 'is_season_total',
 '_name_norm',
 'xg_source',
 'xag_source']

In [19]:
drop_cols = [
    "_ss_merge_failed",
    "_name_norm",
    "xg_source",
    "xag_source",
    "sofascore_team_id",
    "ground_duels_won_pct",
    "set_piece_conversion",
    "scoring_frequency"
]

In [20]:
categorical_cols = [
    "player",
    "team",
    "pos",
    "league",
    "season",
    "is_season_total"
]

In [21]:
id_cols = [
    "understat_id",
    "sofascore_id"
]

In [22]:
special_cols = [
    "sofascore_rating"
]

In [23]:
excluded_from_sum = (
    rate_cols
    + id_cols
    + special_cols
    + categorical_cols
    + drop_cols
)

In [24]:
sum_candidates = [
    col for col in numeric_cols
    if col not in excluded_from_sum
]

sum_candidates

['games',
 'minutes',
 'goals',
 'assists',
 'shots',
 'key_passes',
 'yellow_cards',
 'red_cards',
 'npg',
 'xg',
 'xag',
 'npxg',
 'xg_chain',
 'xg_buildup',
 'ninety_s',
 'sofascore_rating_total',
 'sofascore_rating_count',
 'totw_appearances',
 'starts',
 'tackles',
 'tackles_won',
 'interceptions',
 'clearances',
 'blocked_shots',
 'outfield_blocks',
 'errors_leading_to_goal',
 'errors_leading_to_shot',
 'dribbled_past',
 'aerials_won',
 'aerials_lost',
 'dribbles_completed',
 'dribbles_attempted',
 'ground_duels_won',
 'duels_won',
 'duels_lost',
 'passes_total',
 'passes_completed',
 'passes_inaccurate',
 'passes_final_third',
 'passes_opp_half',
 'passes_own_half',
 'passes_opp_half_total',
 'passes_own_half_total',
 'long_balls_total',
 'long_balls_completed',
 'crosses_total',
 'crosses_completed',
 'chipped_passes_total',
 'chipped_passes_completed',
 'pass_to_assist',
 'attempt_assists',
 'big_chances_created',
 'big_chances_missed',
 'goals_inside_box',
 'goals_outside_box',
 'goals_headed',
 'goals_left_foot',
 'goals_right_foot',
 'goals_penalty',
 'goals_freekick',
 'own_goals',
 'goals_assists',
 'hit_woodwork',
 'shots_inside_box',
 'shots_outside_box',
 'shots_on_target',
 'shots_off_target',
 'shots_set_piece',
 'touches',
 'possession_lost',
 'possession_won_att_third',
 'dispossessed',
 'ball_recoveries',
 'fouls',
 'fouled',
 'offsides',
 'yellow_red_cards',
 'direct_red_cards',
 'pens_taken',
 'pens_conceded',
 'pens_won',
 'pen_miss',
 'pen_post',
 'pen_on_target',
 'saves',
 'saves_caught',
 'saves_parried',
 'saves_inside_box',
 'saves_outside_box',
 'goals_conceded',
 'goals_conceded_inside_box',
 'goals_conceded_outside_box',
 'goals_prevented',
 'clean_sheets',
 'high_claims',
 'crosses_not_claimed',
 'punches',
 'runs_out',
 'runs_out_successful',
 'goal_kicks',
 'pens_saved',
 'pens_faced']

In [25]:
sum_cols = sum_candidates

In [26]:
classified_cols = (
    drop_cols
    + categorical_cols
    + id_cols
    + sum_cols
    + rate_cols
    + special_cols
)

unclassified_cols = [
    col for col in df_domestic.columns
    if col not in classified_cols
]

unclassified_cols

[]

In [27]:
categorical_aggregate_cols = [
    "team",
    "pos",
    "league"
]

In [28]:
group_cols = [
    "player",
    "season"
]

Para la creación del dataset procesado de rendimiento en las ligas domésticas de las Big 5, debido a la existencia de jugadores que han participado en varias ligas durante una misma temporada, se clasifican las variables en diferentes categorías para realizar una correcta agregación de los datos. Esta clasificación permite diferenciar entre variables acumulativas, ratios y porcentajes, y métricas de rendimiento normalizadas por cada 90 minutos.

##### Creación del pipeline para la agregación - player + season

In [8]:
# Función para agregar variables categóricas

def aggregate_unique(values):
    values = values.dropna().unique()

    if len(values) == 0:
        return np.nan

    if len(values) == 1:
        return values[0]

    return " | ".join(map(str, values))

In [9]:
# Función destinada a jugadores con 2 equipos de una misma liga en una misma temporada, para que se consideren como 2 equipos diferentes

def aggregate_unique_split(values):
    unique_values = set()

    for value in values.dropna():
        for item in str(value).split(","):
            item = item.strip()
            if item:
                unique_values.add(item)

    if len(unique_values) == 0:
        return np.nan

    return " | ".join(sorted(unique_values))

In [10]:
# Función para conteo de número de equipos por temporada y si cambió de equipo o no

def count_unique_split(values):
    unique_values = set()

    for value in values.dropna():
        for item in str(value).split(","):
            item = item.strip()
            if item:
                unique_values.add(item)

    return len(unique_values)

In [11]:
# Variables categóricas

categorical_aggregate_cols = [
    "team",
    "pos",
    "league"
]

In [12]:
# Relaciones para calcular porcentajes

percentage_map = {

    "tackles_won_pct": (
        "tackles_won",
        "tackles"
    ),

    "aerials_won_pct": (
        "aerials_won",
        ["aerials_won", "aerials_lost"]
    ),

    "dribbles_pct": (
        "dribbles_completed",
        "dribbles_attempted"
    ),

    "duels_won_pct": (
        "duels_won",
        ["duels_won", "duels_lost"]
    ),

    "pass_completion_pct": (
        "passes_completed",
        "passes_total"
    ),

    "long_balls_pct": (
        "long_balls_completed",
        "long_balls_total"
    ),

    "crosses_pct": (
        "crosses_completed",
        "crosses_total"
    ),

    "goal_conversion_pct": (
        "goals",
        "shots"
    ),

    "pen_conversion_pct": (
        "goals_penalty",
        "pens_taken"
    ),

    "passes_opp_half_pct": (
        "passes_opp_half",
        "passes_opp_half_total"
    ),

    "passes_own_half_pct": (
        "passes_own_half",
        "passes_own_half_total"
    ),

    "chipped_passes_pct": (
        "chipped_passes_completed",
        "chipped_passes_total"
    ),

    "shots_inside_box_conversion_pct": (
        "goals_inside_box",
        "shots_inside_box"
    ),

    "shots_outside_box_conversion_pct": (
        "goals_outside_box",
        "shots_outside_box"
    )
}

In [13]:
# Métricas por 90 minutos

per90_map = {

    "goals_per90": "goals",

    "assists_per90": "assists",

    "npg_per90": "npg",

    "xg_per90": "xg",

    "xag_per90": "xag",

    "npxg_per90": "npxg",

    "xg_chain_per90": "xg_chain",

    "xg_buildup_per90": "xg_buildup",

    "shots_per90": "shots",

    "key_passes_per90": "key_passes",

    "tackles_won_per90": "tackles_won",

    "interceptions_per90": "interceptions",

    "big_chances_created_per90": "big_chances_created",

    "dribbles_per90": "dribbles_completed"
}

In [14]:
# Función principal de agregación

def aggregate_player_season(df):
    
    df = df.drop(columns=drop_cols, errors="ignore").copy()

    # Agrupación por jugador y temporada

    grouped = df.groupby(
        ["player", "season"],
        sort=False
    )

    # 1. VARIABLES ACUMULATIVAS

    df_sum = (
        grouped[sum_cols]
        .sum(min_count=1)
    )

    # 2. VARIABLES CATEGÓRICAS

    df_team = (
        grouped["team"]
        .agg(aggregate_unique_split)
        .rename("team")
    )

    df_other_cat = (
        grouped[["pos", "league"]]
        .agg(aggregate_unique)
    )
    
    df_cat = pd.concat(
        [
            df_team,
            df_other_cat
        ],
        axis=1
    )

    # 3. IDENTIFICADORES

    df_ids = (
        grouped[id_cols]
        .first()
    )

    # 4. UNIÓN DE LOS BLOQUES

    result = pd.concat(
        [
            df_sum,
            df_cat,
            df_ids
        ],
        axis=1
    ).reset_index()

    # 5. NÚMERO DE EQUIPOS Y LIGAS

    counts = (
        grouped
        .agg(
            team_count=("team", count_unique_split),
            league_count=("league", "nunique")
        )
        .reset_index(drop=True)
    )
    
    result["team_count"] = counts["team_count"]
    result["league_count"] = counts["league_count"]

    # 6. INDICADORES DE CAMBIO

    result["changed_team"] = (
        result["team_count"] > 1
    ).astype(int)

    result["changed_league"] = (
        result["league_count"] > 1
    ).astype(int)

    # 7. SOFASCORE RATING

    result["sofascore_rating"] = np.where(
        result["sofascore_rating_count"] > 0,
        result["sofascore_rating_total"]
        / result["sofascore_rating_count"],
        np.nan
    )

    # 8. MÉTRICAS PORCENTUALES

    for col, (numerator, denominator) in percentage_map.items():

        if isinstance(denominator, list):
            denominator_value = (
                result[denominator]
                .sum(axis=1)
            )
        else:
            denominator_value = result[denominator]

        result[col] = np.where(
            denominator_value > 0,
            result[numerator]
            / denominator_value
            * 100,
            np.nan
        )

    # 9. MÉTRICAS POR 90 MINUTOS

    for rate_col, total_col in per90_map.items():

        result[rate_col] = np.where(
            result["minutes"] > 0,
            result[total_col]
            / result["minutes"]
            * 90,
            np.nan
        )

    # 10. XG OVERPERFORMANCE

    result["xg_overperformance"] = (
        result["goals"]
        - result["xg"]
    )

    result["npxg_overperformance"] = (
        result["npg"]
        - result["npxg"]
    )

    return result

##### Aplicación del pipeline de agregación para dataset de ligas domésticas - Big 5

In [127]:
df_domestic_processed = aggregate_player_season(df_domestic)

##### Comprobaciones tras aplicación del pipeline

In [134]:
# Cálculos de porcentajes coherentes

df_domestic_processed[["tackles_won", "tackles", "tackles_won_pct"]].head()

   tackles_won  tackles  tackles_won_pct
0          0.0      0.0              NaN
1         28.0     48.0        58.333333
2         35.0     66.0        53.030303
3          0.0      0.0              NaN
4          1.0      1.0       100.000000

In [135]:
# Una fila por jugador y temporada

df_domestic_processed.duplicated(
    subset=["player", "season"]
).sum()

np.int64(0)

In [136]:
# Comprobar que los jugadores que cambiaron de liga mantienen toda la información agregada

df_domestic_processed[
    df_domestic_processed["league_count"] > 1
][
    [
        "player",
        "season",
        "team",
        "league",
        "team_count",
        "league_count",
        "changed_team",
        "changed_league",
        "minutes",
        "goals"
    ]
].head(20)

,player,season,team,league,team_count,league_count,changed_team,changed_league,minutes,goals
10,Gabriel,2023-2024,Arsenal | Atletico Madrid | Valencia,England Premier League | Spain La Liga,3,2,1,1,4871,3
25,Bertrand Traoré,2023-2024,Aston Villa | Villarreal,England Premier League | Spain La Liga,2,2,1,1,575,1
39,Leander Dendoncker,2023-2024,Aston Villa | Napoli,England Premier League | Italy Serie A,2,2,1,1,133,1
64,Enes Ünal,2023-2024,Bournemouth | Getafe,England Premier League | Spain La Liga,2,2,1,1,416,2
65,Hamed Junior Traore,2023-2024,Bournemouth | Napoli,England Premier League | Italy Serie A,2,2,1,1,418,0
83,Romain Faivre,2023-2024,Bournemouth | Lorient,England Premier League | France Ligue 1,2,2,1,1,1473,5
116,Anssumane Fati,2023-2024,Barcelona | Brighton,England Premier League | Spain La Liga,2,2,1,1,482,2
120,Carlos Baleba,2023-2024,Brighton | Lille,England Premier League | France Ligue 1,2,2,1,1,1368,0
136,Mahmoud Dahoud,2023-2024,Brighton | VfB Stuttgart,England Premier League | Germany Bundesliga,2,2,1,1,622,1
152,David Datro Fofana,2023-2024,Burnley | Union Berlin,England Premier League | Germany Bundesliga,2,2,1,1,1560,5
163,Lorenz Assignon,2023-2024,Burnley | Rennes,England Premier League | France Ligue 1,2,2,1,1,2259,2
167,Maxime Estève,2023-2024,Burnley | Montpellier,England Premier League | France Ligue 1,2,2,1,1,2316,1
188,Ian Maatsen,2023-2024,Borussia Dortmund | Chelsea,England Premier League | Germany Bundesliga,2,2,1,1,1457,2
239,Beto,2023-2024,Everton | Udinese,England Premier League | Italy Serie A,2,2,1,1,979,3
305,Ryan Gravenberch,2023-2024,Bayern Munich | Liverpool,England Premier League | Germany Bundesliga,2,2,1,1,1122,1
347,Jéremy Doku,2023-2024,Manchester City | Rennes,England Premier League | France Ligue 1,2,2,1,1,1726,4
374,Donny van de Beek,2023-2024,Eintracht Frankfurt | Manchester United,England Premier League | Germany Bundesliga,2,2,1,1,361,0
376,Facundo Pellistri,2023-2024,Granada | Manchester United,England Premier League | Spain La Liga,2,2,1,1,1386,2
377,Hannibal Mejbri,2023-2024,Manchester United | Sevilla,England Premier League | Spain La Liga,2,2,1,1,215,1
379,Jadon Sancho,2023-2024,Borussia Dortmund | Manchester United,England Premier League | Germany Bundesliga,2,2,1,1,1051,2

In [140]:
df_domestic_processed[
    df_domestic_processed["team_count"] > 2
][
    [
        "player",
        "season",
        "team",
        "league",
        "team_count",
        "league_count",
        "changed_team",
        "changed_league"
    ]
].head(20)

,player,season,team,league,team_count,league_count,changed_team,changed_league
10,Gabriel,2023-2024,Arsenal | Atletico Madrid | Valencia,England Premier League | Spain La Liga,3,2,1,1
1356,Idrissa Gueye,2025-2026,Everton | Metz | Udinese,England Premier League | France Ligue 1 | Ital...,3,3,1,1

In [139]:
df_domestic_processed[
    df_domestic_processed["league_count"] > 2
][
    [
        "player",
        "season",
        "team",
        "league",
        "team_count",
        "league_count",
        "changed_team",
        "changed_league"
    ]
].head(20)

,player,season,team,league,team_count,league_count,changed_team,changed_league
1356,Idrissa Gueye,2025-2026,Everton | Metz | Udinese,England Premier League | France Ligue 1 | Ital...,3,3,1,1

In [145]:
df_domestic_processed[
    df_domestic_processed["player"] == "Idrissa Gueye"][
        ["season", "goals", "shots", "goal_conversion_pct"]
]

         season  goals  shots  goal_conversion_pct
242   2023-2024      4     26            15.384615
774   2024-2025      0     27             0.000000
1356  2025-2026      3     51             5.882353

In [146]:
df_domestic_processed.to_csv(
    "../data/processed_data/domestic_player_seasons.csv",
    index=False
)

In [4]:
df["league"].value_counts()

league
All Competitions            3361
UEFA Europa League          2740
UEFA Champions League       2477
England EFL Championship    2189
Spain La Liga               1783
Italy Serie A               1775
England Premier League      1668
Portugal Primeira Liga      1645
France Ligue 1              1618
Netherlands Eredivisie      1567
Germany Bundesliga          1474
Name: count, dtype: int64

In [5]:
ALL_COMPS = [comp for comp in df["league"].value_counts().index if comp != 'All Competitions']

In [7]:
df_all_comps = df_domestic = df[df["league"].isin(ALL_COMPS)].copy()

In [29]:
df_all_comps_processed = aggregate_player_season(df_all_comps)

In [34]:
df_all_comps_processed[df_all_comps_processed['player'] == 'Andre Dozzell']

,player,season,games,minutes,goals,assists,shots,key_passes,yellow_cards,red_cards,...,xg_chain_per90,xg_buildup_per90,shots_per90,key_passes_per90,tackles_won_per90,interceptions_per90,big_chances_created_per90,dribbles_per90,xg_overperformance,npxg_overperformance
1,Andre Dozzell,2023-2024,35,2613,3,1,23,30,4,1,...,0.0,0.0,0.792193,1.033295,0.861079,0.826636,0.137773,0.275545,1.86,0.0
1146,Andre Dozzell,2024-2025,39,2826,2,1,16,17,11,0,...,0.0,0.0,0.509554,0.541401,1.019108,0.796178,0.127389,0.159236,-0.47,0.0
1843,Andre Dozzell,2025-2026,37,3157,2,1,16,25,8,0,...,0.0,0.0,0.456129,0.712702,0.598670,0.712702,0.085524,0.456129,1.05,0.0

In [ ]:
df_all_comps_processed[(df_all_comps_processed['team_count'] < 2) & (df_all_comps_processed["league"] == 'Spain La Liga')].head(10)

league
England EFL Championship                                               2048
UEFA Europa League                                                     1570
Spain La Liga                                                          1296
Portugal Primeira Liga                                                 1294
Italy Serie A                                                          1222
Netherlands Eredivisie                                                 1191
France Ligue 1                                                         1148
England Premier League                                                 1033
Germany Bundesliga                                                     1001
UEFA Champions League                                                   861
England Premier League | UEFA Champions League                          201
Italy Serie A | UEFA Champions League                                   165
Netherlands Eredivisie | UEFA Europa League                             155
Netherlands Eredivisie | UEFA Champions League                          122
Portugal Primeira Liga | UEFA Champions League                          120
Spain La Liga | UEFA Champions League                                   119
Spain La Liga | UEFA Europa League                                      111
Portugal Primeira Liga | UEFA Europa League                             109
Germany Bundesliga | UEFA Champions League                               95
France Ligue 1 | UEFA Europa League                                      72
England Premier League | UEFA Europa League                              59
Italy Serie A | UEFA Europa League                                       58
UEFA Champions League | UEFA Europa League                               56
Germany Bundesliga | UEFA Europa League                                  31
Portugal Primeira Liga | UEFA Champions League | UEFA Europa League      31
France Ligue 1 | UEFA Champions League                                   18
Netherlands Eredivisie | UEFA Champions League | UEFA Europa League      18
Italy Serie A | UEFA Champions League | UEFA Europa League               15
Name: count, dtype: int64